-- Run this in Supabase SQL Editor to import all your meals

insert into meals (name, diet_tags, ingredients) values
('Vegetable Poha', array['vegetarian','light'], array[]::text[]),
('Dosa', array['vegetarian'], array[]::text[]),
('Idli Sambar', array['vegetarian','light'], array[]::text[]),
('Muesli', array['vegetarian','light'], array[]::text[]),
('Moong Paneer Chilla', array['vegetarian','high-protein'], array[]::text[]),
('Appe (Vegetable)', array['vegetarian','light'], array[]::text[]),
('Paneer Cheela', array['vegetarian','high-protein'], array[]::text[]),
('Poha', array['vegetarian','light'], array[]::text[]),
('Sevaiyan', array['vegetarian'], array[]::text[]),
('Suji Uttapam', array['vegetarian'], array[]::text[]),
('Bhelpuri', array['vegetarian','light'], array[]::text[]),
('Paneer Paratha', array['vegetarian'], array[]::text[]),
('Aloo Sandwich', array['vegetarian'], array[]::text[]),
('Sabudana Khichdi', array['vegetarian'], array[]::text[]),
('Upma', array['vegetarian','light'], array[]::text[]),
('Dal Makhni + Roti', array['vegetarian','high-protein'], array[]::text[]),
('Moong Dal + Ghiya/Tori Sabzi', array['vegetarian','light','low-carb'], array[]::text[]),
('Palak Paneer + Roti', array['vegetarian','high-protein'], array[]::text[]),
('Chole Chawal + Hummus', array['vegetarian','high-protein'], array[]::text[]),
('Kadhi + Mix Veg Sabzi + Roti', array['vegetarian'], array[]::text[]),
('Bhindi Tur Dal Rice', array['vegetarian'], array[]::text[]),
('Baingan Bharta', array['vegetarian','low-carb'], array[]::text[]),
('Kadai Paneer', array['vegetarian','high-protein'], array[]::text[]),
('Kadi', array['vegetarian','light'], array[]::text[]),
('Bhindi', array['vegetarian','low-carb','light'], array[]::text[]),
('Ghiya Sabzi', array['vegetarian','light','low-carb'], array[]::text[]),
('Rajma', array['vegetarian','high-protein'], array[]::text[]),
('Chole', array['vegetarian','high-protein'], array[]::text[]),
('Dal Makhni', array['vegetarian','high-protein'], array[]::text[]),
('Tur Dal', array['vegetarian','high-protein','light'], array[]::text[]),
('Mung Dal', array['vegetarian','high-protein','light'], array[]::text[]),
('Paneer Pulao', array['vegetarian','high-protein'], array[]::text[]),
('Paneer Bhurji', array['vegetarian','high-protein'], array[]::text[]),
('Idli Fry', array['vegetarian'], array[]::text[]),
('Hummus Wrap', array['vegetarian'], array[]::text[]),
('Pasta', array['vegetarian'], array[]::text[]),
('Pasta Salad', array['vegetarian','light'], array[]::text[]),
('Kala Chana Salad', array['vegetarian','high-protein','low-carb'], array[]::text[]),
('Rajma Salad', array['vegetarian','high-protein','low-carb'], array[]::text[]),
('Moong Salad', array['vegetarian','high-protein','low-carb'], array[]::text[]),
('Moong Chana Salad', array['vegetarian','high-protein','low-carb'], array[]::text[]),
('Chole Paneer Salad', array['vegetarian','high-protein','low-carb'], array[]::text[]),
('Chola Salad', array['vegetarian','high-protein','low-carb'], array[]::text[]);
